name: Build and deploy HR_Project.Presentation to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v7
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build and publish HR_Project.Presentation
        run: |
          cd HR_Project.Presentation
          dotnet publish -c Release -o ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'your-azure-webapp-name'  # Azure Web App adınızı buraya ekleyin
          slot-name: 'Production'  # Kullanmak istediğiniz slot adınızı buraya ekleyin (isteğe bağlı)
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./HR_Project.Presentation/publish
